[server]
port = 8501              # Porta do app
enableCORS = false       # Desativa CORS para acessos locais/rede
headless = true           # Evita abrir o navegador automaticamente
runOnSave = false         # Evita reload automático ao salvar o script
numThreads = 8

[browser]
gatherUsageStats = false

[global]
unit = "metric"